### ISSUE TITLE
use ds._ not working

### ISSUE THREAD

**Issue by ST9527** [fsanaulla/chronicler-spark#11]
I'm testing my code in mac, I can save data to influxdb using `structured.streaming._` but failed to save data using `ds._`
My code looks like below:

```
case class A(name: String ....)
df = spark.select("xxxxx").as[A]
implicit lazy val influxConf: InfluxConfig =
      InfluxConfig(conf.getString("db.host"), conf.getInt("db.port"), Some(InfluxCredentials(conf.getString("db.user"), conf.getString("db.passwd"))), gzipped = false, None)
implicit val wr: InfluxWriter[A] = new InfluxWriter[A] {
      override def write(obj: A): String = {
         xxxx.to_string
     }
}
df.saveToInfluxDB(conf.getString("db.database"), "xxxxx")
```

It runs without error output, but failed to save data.
I'm guessing it's because something goes wrong when calling `managed(InfluxIO(conf)) ` in `com.github.fsanaulla.chronicler.spark.rdd`

Sorry for my poor English ...

**Comment by fsanaulla** [comment]
Hi, @ST9527. Did you try to pass `onFailure` parameter?

**Comment by ST9527** [comment]
> Hi, @ST9527. Did you try to pass `onFailure` parameter?

Yes, but still print nothing...

**Comment by fsanaulla** [comment]
@ST9527 Can you provide information about your data? Or complete example?

**Comment by ST9527** [comment]
> @ST9527 Can you provide information about your data? Or complete example?

It's basically all of it.Could you send me some example of how it works?

**Comment by fsanaulla** [comment]
@ST9527 is [it](https://github.com/fsanaulla/chronicler-spark/blob/master/spark-ds/src/test/scala/com/github/fsanaulla/chronicler/spark/ds/SparkDatasetSpec.scala) helps? Or should I provide additional examples?

**Comment by fsanaulla** [comment]
@ST9527 should I close this issue?
