### ISSUE TITLE
Compile Failing

### ISSUE THREAD

**Issue by vakilp** [fsanaulla/chronicler-spark#17]
Trying to compile code on a mac and getting the following error:
`
[error] java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
[error] 	at ohnosequences.sbt.GithubRelease$defs$.ghreleaseMediaTypesMap(GithubRelease.scala:45)
[error] 	at ohnosequences.sbt.SbtGithubReleasePlugin$.$anonfun$projectSettings$14(SbtGithubReleasePlugin.scala:29)
[error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:814)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:204)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:221)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:835)
[error] Caused by: java.lang.ClassNotFoundException: javax.activation.MimetypesFileTypeMap
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	at ohnosequences.sbt.GithubRelease$defs$.ghreleaseMediaTypesMap(GithubRelease.scala:45)
[error] 	at ohnosequences.sbt.SbtGithubReleasePlugin$.$anonfun$projectSettings$14(SbtGithubReleasePlugin.scala:29)
[error] 	at sbt.internal.util.Init$Value.$anonfun$apply$3(Settings.scala:814)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$constant$1(INode.scala:204)
[error] 	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:221)
[error] 	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:164)
[error] 	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error] 	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:98)
[error] 	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:835)
[error] java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
`
Any thoughts on what I am doing wrong?

Thank you.

**Comment by fsanaulla** [comment]
Hello, maybe something like this: https://github.com/ohnosequences/sbt-github-release/issues/28

**Comment by fsanaulla** [comment]
@vakilp did it help?

**Comment by vakilp** [comment]
Yes it did. Thank you very much!
