### ISSUE TITLE
Consistencies$ONE$ not defined...

### ISSUE THREAD

**Issue by ondrejspilka** [fsanaulla/chronicler-spark#2]
Hi,

using DataBricks / scala 2.11 / Spark 2.3.1 I am getting 
`java.lang.NoClassDefFoundError: Could not initialize class com.github.fsanaulla.chronicler.core.enums.Consistencies$ONE$
`
Any idea what is wrong? All chronicle jars are 2.11...
Thanks
Ondřej

```

// Create a connection to our InfluxDB
import scala.util.{Success, Failure}
import scala.concurrent.ExecutionContext.Implicits.global

import com.github.fsanaulla.chronicler.macros.Macros
import com.github.fsanaulla.chronicler.macros.annotations.{field, tag}
import com.github.fsanaulla.chronicler.core.model.InfluxWriter
import com.github.fsanaulla.chronicler.core.model.Point
import com.github.fsanaulla.chronicler.core.enums.{Consistencies, Epochs, Precisions}
import com.github.fsanaulla.chronicler.core.model.{InfluxConfig, InfluxCredentials}
import com.github.fsanaulla.chronicler.async.Influx
import com.github.fsanaulla.chronicler.spark.ds._ // DataFrame = DataSet[Row]
import com.github.fsanaulla.chronicler.spark.structured.streaming._


implicit lazy val influxConf: InfluxConfig = InfluxConfig("host", 8086, Some(InfluxCredentials("user", "passwrod")), gzipped = false)

//case class Entity(@tag sensor: String, @field createdAt: Int, @field tempVal: Double, @field humVal: Double)
//implicit val wr: InfluxWriter[Entity] = Macros.writer[Entity]
implicit val wr: InfluxWriter[Row] = new InfluxWriter[Row] {
   override def write(o: Row): String = {
     val sb = StringBuilder.newBuilder
     
     // Query looks like: <tags> <fields> <timestamp RFC3339>
     sb.append(s"sensor=${o(0)}")
       .append(" ") 
       .append("value=")
       .append(o(1))
     
     sb.toString()
   }
}

// Create our stream
val streamInflux = messages.writeStream // Create a WriteStream

var inflStream = streamInflux.saveToInflux("crwMetrics", "RAP5", Consistencies.ONE)

inflStream.start()
```

**Comment by fsanaulla** [comment]
Hello @ondrejspilka. Thank you for your report. Is it a complete example?

**Comment by ondrejspilka** [comment]
Hi,

It is missing messages query, which can be whatever...for me it is EventHub
stream...
The error appears only if start() method is called.

Thanks
Ondrej

**Comment by fsanaulla** [comment]
@ondrejspilka I'm asking because I can't see `main` method and `awaitTermination` of a stream? Does it exist somewhere in the code?

**Comment by ondrejspilka** [comment]
No it is spark streaming in DataBricks notebook.
Should be called anyway?

**Comment by fsanaulla** [comment]
@ondrejspilka yes, you need to have `awaitTermination` at the end of your stream. Can you show me your notebook dependencies list?

**Comment by ondrejspilka** [comment]
Hi Faiaz,

so I removed all Maven libraries, downloaded all JARs manually and added
awaitTermination()...still no success

Cluster is Scala 2.11, ApacheSpark  is  2.3.1.
Libraries explicitly loaded in DataBricks.
[image: image.png]

Ondřej Spilka


pá 21. 9. 2018 v 18:04 odesílatel Faiaz Sanaulla <notifications@github.com>
napsal:

**Comment by ondrejspilka** [comment]
And also tried to remove all JARs and add chronicler dependencies as Maven
repos, with no success..

Regards
Ondřej

[image: image.png]



Ondřej Spilka


pá 21. 9. 2018 v 18:04 odesílatel Faiaz Sanaulla <notifications@github.com>
napsal:

**Comment by fsanaulla** [comment]
@ondrejspilkaI think the main problem, not in the way how dependencies injected. In your first comment i can see `import com.github.fsanaulla.chronicler.async.Influx` rudimental dependencies, that may in some case create issues. Also, I can't see your dependencies in the previous comment, can you fix it?
Thank you.

**Comment by ondrejspilka** [comment]
Hi,

please see ignore it. I have recreated cluster and installed everzthing
from scratch and it works.
I woudl say there was some 2.12 mismatch.

Anyway thanks!
And BTW, do you pan to maintain the package? I see there is couple of
months of inactivity...

Ondřej Spilka


po 24. 9. 2018 v 12:09 odesílatel Faiaz Sanaulla <notifications@github.com>
napsal:

**Comment by fsanaulla** [comment]
@ondrejspilka yep, I will maintain it. So can I close this issue?

**Comment by ondrejspilka** [comment]
Sure, close it.
Just last question...how timestamp is passed when case class is used?
Eventually some example of spark streaming using case class would be nice.

Anyway thanks.
Ondrej

**Comment by fsanaulla** [comment]
To see how set timestamp look [here](https://github.com/fsanaulla/chronicler/blob/master/docs/macros.md). Usage of spark streaming with case classes you can find in [test](https://github.com/fsanaulla/chronicler-spark/blob/master/spark-streaming/src/test/scala/com/github/fsanaulla/chronicler/spark/streaming/SparkStreamingSpec.scala#L40). If you have other questions feel free to open an issue or ask me on [gitter](https://gitter.im/chronicler-scala/Lobby/?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

Thank you!

**Comment by ondrejspilka** [comment]
Perfect,missed the docs.
Thanks
Ondrej
